openapi: 3.0.0
info:
  description: A API permite que você envie e receba mensagens do WhatsApp utilizando a plataforma Notifish. Crie uma conta no Notifish e obtenha as informações necessárias para autenticação.
  title: API Notifish Documentação
  version: 1.0.0
servers:
  - url: http://{domain_url}.notifish.com/api/v1/{instance_uuid}
    variables:
      domain_url:
        default: MEU_DOMINIO
        description: Domain of sistem
      instance_uuid:
        default: MINHA_INSTANCE
        description: UUID of the instance
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
  - name: Instâncias
    description: Operações relacionadas a instâncias do WhatsApp
  - name: Mensagens
    description: Operações relacionadas a mensagens do WhatsApp
paths:
  /api/v1/whatsapp/message:
    post:
      tags:
        - Mensagens
      requestBody:
        content:
          application/json:
            schema:
              properties:
                phone:
                  type: string
                message:
                  type: string
              type: object
      responses:
        '200':
          description: Mensagem enviada com sucesso
      summary: Enviar mensagem

  /authorize/register/tenant:
    post:
      tags:
        - Instâncias
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tenant:
                  type: object
                  properties:
                    corporate_name:
                      type: string
                    corporate_responsable:
                      type: string
                    corporate_fantasy_name:
                      type: string
                    corporate_domain_tenant:
                      type: string
                    corportate_description:
                      type: string
                    corporte_address:
                      type: string
                    corporate_complement:
                      type: string
                    corporate_number:
                      type: string
                    corporate_city:
                      type: string
                    acronym_uf:
                      type: string
                    corporate_zipcode:
                      type: string
                    corporate_cpf_cnpj:
                      type: string
                    corporate_phone:
                      type: string
                    corporate_phone2:
                      type: string
                    corporate_whatsapp:
                      type: string
                    corporate_email:
                      type: string
                    corporate_plan_uuid:
                      type: string
                details:
                  type: object
                  properties:
                    site_registration:
                      type: string
                    site_registration_name:
                      type: string
                    your_identifier:
                      type: string
              type: object
      responses:
        '201':
          description: Registro de tenant realizado com sucesso
      summary: Registro de Tenant

  /authorize/generate-token:
    put:
      tags:
        - Autenticação
      requestBody:
        content:
          application/json:
            schema:
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                token:
                  type: object
                  properties:
                    name:
                      type: string
              type: object
      responses:
        '201':
          description: Token gerado com sucesso
      summary: Gerar token

  /testing/api/auth/user:
    get:
      tags:
        - Autenticação
      responses:
        '200':
          description: Autenticação testada com sucesso
      summary: Testar login

  /whatsapp/add-instance:
    post:
      tags:
        - Instâncias
      requestBody:
        content:
          application/json:
            schema:
              properties:
                whatsapp:
                  type: string
                nickname:
                  type: string
                url_callback:
                  type: string
              type: object
      responses:
        '200':
          description: Instância adicionada com sucesso
      summary: Adicionar instância

  /whatsapp/login:
    post:
      tags:
        - Instâncias
      responses:
        '200':
          description: Sessão iniciada com sucesso
      summary: Iniciar sessão

  /whatsapp/status:
    get:
      tags:
        - Instâncias
      responses:
        '200':
          description: Status da instância retornado com sucesso
      summary: Status da conexão

  /whatsapp/restart:
    get:
      tags:
        - Instâncias
      responses:
        '200':
          description: Instância reiniciada com sucesso
      summary: Reiniciar instância

  /whatsapp/list-instances:
    get:
      tags:
        - Instâncias
      responses:
        '200':
          description: Lista de instâncias retornada com sucesso
      summary: Lista de instâncias

  /whatsapp/message:
    post:
      tags:
        - Mensagens
      requestBody:
        content:
          application/json:
            schema:
              properties:
                recipient_phone:
                  type: string
                message:
                  type: string
                identifier:
                  type: string
                link:
                  type: boolean
                typing:
                  type: string
                delayMessage:
                  type: integer
              type: object
      responses:
        '200':
          description: Mensagem enviada com sucesso
      summary: Enviar mensagem

  /whatsapp/send-media:
    post:
      tags:
        - Mensagens
      requestBody:
        content:
          application/json:
            schema:
              properties:
                recipient_phone:
                  type: string
                identifier:
                  type: string
                delay:
                  type: integer
                media:
                  type: object
                  properties:
                    type:
                      type: string
                    caption:
                      type: string
                    archive:
                      type: string
                    filename:
                      type: string
              type: object
      responses:
        '200':
          description: Mídia enviada com sucesso
      summary: Enviar mídia

  /whatsapp/send-narrated-audio:
    post:
      tags:
        - Mensagens
      requestBody:
        content:
          application/json:
            schema:
              properties:
                recipient_phone:
                  type: string
                identifier:
                  type: string
                delay:
                  type: integer
                audio:
                  type: object
                  properties:
                    url:
                      type: string
              type: object
      responses:
        '200':
          description: Áudio narrado enviado com sucesso
      summary: Enviar áudio narrado

  /whatsapp/message/reprocess:
    post:
      tags:
        - Mensagens
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: array
                  items:
                    type: integer
              type: object
      responses:
        '200':
          description: Mensagens reprocessadas com sucesso
      summary: Reprocessar mensagem
